name: carrermodetracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  
    sdk: flutter
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  go_router: ^14.8.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 

dev_dependencies:
  build_runner: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
